# Generated by Django 5.0.6 on 2024-07-13 10:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLandingPageImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing_pages_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('nav_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_images', to='backend.postnavitem')),
            ],
            options={
                'db_table': 'landing_pages_images',
                'ordering': ['position'],
            },
        ),
    ]
