# Generated by Django 5.0.6 on 2024-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_postlandingpageimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlandingpageimages',
            name='title_data',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
