# Generated by Django 5.0.6 on 2024-07-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_postlandingpageimages_title_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlandingpageimages',
            name='section',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
