# Generated by Django 5.0.6 on 2024-07-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_postlandingpageimages_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlandingpageimages',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
